ARG CADDY_VERSION=2.8
FROM caddy:${CADDY_VERSION}-alpine

ENV TZ=Europe/Rome

RUN apk add --no-cache tzdata && \
    caddy add-package github.com/caddyserver/transform-encoder \
                      github.com/lucaslorentz/caddy-docker-proxy/v2 \
                      github.com/mholt/caddy-l4 \
                      github.com/abiosoft/caddy-exec

CMD ["caddy", "docker-proxy"]
