ARG CADDY_VERSION=2.10
FROM caddy:${CADDY_VERSION}-builder AS builder

RUN xcaddy build \
    --with github.com/lucaslorentz/caddy-docker-proxy/v2@v2.10.0 \
    --with github.com/caddyserver/transform-encoder

FROM caddy:${CADDY_VERSION}

ENV SERVICE=caddy \
    TZ=Europe/Rome

LABEL org.opencontainers.image.source=https://github.com/Neomediatech/${SERVICE} \
      org.opencontainers.package.name=caddy

RUN apk add --no-cache tzdata

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

CMD ["caddy", "docker-proxy"]
